spring:
  security:
    oauth2:
      client:
        registration:
          custom:
             client-id: ourclient
             client-secret: pass123
             authorization-grant-type: client_credentials
        provider:
          custom:
            token-uri: http://localhost:8585/oauth/token